image: node:12-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master
